// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDynqnBFIJucM1dvnoxsJo_K6lDSDFu4M',
    appId: '1:926264768467:web:6a07d11f0cf6e4f64f6126',
    messagingSenderId: '926264768467',
    projectId: 'ceylon-trekker',
    authDomain: 'ceylon-trekker.firebaseapp.com',
    storageBucket: 'ceylon-trekker.firebasestorage.app',
    measurementId: 'G-LCY9P7XPM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClMdiTieWjDc1iuZ5euI8RRIoVxXO2JBI',
    appId: '1:926264768467:android:694bbbbf7e0d26a34f6126',
    messagingSenderId: '926264768467',
    projectId: 'ceylon-trekker',
    storageBucket: 'ceylon-trekker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUlWbQP8OatNwG1uJyWTpWxZVjmNGBS4Y',
    appId: '1:926264768467:ios:7609ac874b755ca54f6126',
    messagingSenderId: '926264768467',
    projectId: 'ceylon-trekker',
    storageBucket: 'ceylon-trekker.firebasestorage.app',
    iosBundleId: 'com.example.ceylonTrekker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUlWbQP8OatNwG1uJyWTpWxZVjmNGBS4Y',
    appId: '1:926264768467:ios:7609ac874b755ca54f6126',
    messagingSenderId: '926264768467',
    projectId: 'ceylon-trekker',
    storageBucket: 'ceylon-trekker.firebasestorage.app',
    iosBundleId: 'com.example.ceylonTrekker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDynqnBFIJucM1dvnoxsJo_K6lDSDFu4M',
    appId: '1:926264768467:web:63744a76f39923c44f6126',
    messagingSenderId: '926264768467',
    projectId: 'ceylon-trekker',
    authDomain: 'ceylon-trekker.firebaseapp.com',
    storageBucket: 'ceylon-trekker.firebasestorage.app',
    measurementId: 'G-BRX4BHVX7Q',
  );
}
